### ISSUE TITLE
Support outside France

### ISSUE THREAD

**Issue by YotomiY** [TGA25dev/Pronote-Class-Notifier#3]
Hello,
I just tested the script and I just wanted to know when the international version will be out. When I put another location than France I receive the message: "nous supportont que là France actuellement". I think it should be possible to make the user input them selfs the school information.
Also when do you plan to add notifications to new notes (just a suggestion)
Thank you.

**Comment by TGA25dev** [comment]
Hi !
For the moment I didn't implemented international schools support as the api that retrieve the pronote login url only support's french schools. However I could think of something, like put an entry for the pronote url so the user can put it itself regardless of the api. 

For the new note notification it's something that I have thought about, but I am currently working on hosting the project myself so it's just an idea for the moment... 

btw, you speak french right ?

**Comment by YotomiY** [comment]
Oui je parle français, pour le support international je pense que vous pourriez mettre un système de mise en place manuelle.

**Comment by TGA25dev** [comment]
Ah parfait alors ! Oui c'etait mon idée aussi, si le système detecte que c'est un autre pays que la France il affiche un input pour le lien de connexion et récupère également la timezone de ce pays.

**Comment by YotomiY** [comment]
Juste pour savoir, tu va pouvoir faire ceci quand? J'ai vraiment besoin du système. 😅

**Comment by YotomiY** [comment]
Exactement désoler je n'avait pas remarqué. Pour l'hébergement vous penser faire pour vous même ou pour héberger le projet complet. Dite moi si vous avez besoin d'aide.

**Comment by TGA25dev** [comment]
Pas de problème, pour les matières manquantes je complète le fichier au fur et à mesure que j'en découvre des nouvelles 😅. 
Pour l'hebergement justement je travaille pour que quiconque puisse s'en servir. 
J'ai vu aussi que vous aviez forké le projet, j'avoue ne pas être très doué pour la collaboration sur Github mais si vous voulez aider faites vous plaisir 😂.

**Comment by YotomiY** [comment]
D'accord merci!!

**Comment by YotomiY** [comment]
Bonjour, 
J'ai essayer de run le script mais j'ai cette erreur
```
 Uncaught exception: expected token to be a str, received NoneType instead
Traceback: Traceback (most recent call last):
  File "C:\Users\\Desktop\Pronote-Notifier\pronote_main_code.py", line 480, in <module>
    bot.run(token)
  File "C:\Users\\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Users\\.pyenv\pyenv-win\versions\3.10.0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\\.pyenv\pyenv-win\versions\3.10.0\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\discord\client.py", line 858, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\discord\client.py", line 786, in start
    await self.login(token)
  File "C:\Users\\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\discord\client.py", line 617, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead
```

**Comment by TGA25dev** [comment]
Alors 😅, le problème de ce projet était l'hebergement je ne savais pas sur quelle plateforme mettre mon code, du coup j'ai passé tout ça sur un bot Discord (pas la meilleure idée que j'ai eu je vous l'accorde).

Le problème que vous avez ici est que le bot cherche un token dans le fichier `Token/pronote_bot_token.env` or par mesure de sécurité je n'ai pas envoyé ce token sur le repo. Vous pouvez en générer un sur le portail dev de Discord si vous voulez ou essayer de retirer toute allusion au bot pour faire juste tourner le code en local.

**Comment by TGA25dev** [comment]
C'est cette partie qui en est en charge :
```
dotenv.load_dotenv("Token/pronote_user.env")
secured_username = os.getenv("User")
logger.debug("Pronote username has been loaded.")

dotenv.load_dotenv("Token/pronote_password.env")
secured_password = os.getenv("Password")
logger.debug("Pronote password has been loaded.")

dotenv.load_dotenv("Token/pronote_bot_token.env")
token = os.getenv("Token")
logger.debug("Pronote Bot token has been loaded.")
```

**Comment by YotomiY** [comment]
Merci sa marche!
Mais pour l'hebergement 24/7 daki et Discloud ne marche pas vraiment...

**Comment by TGA25dev** [comment]
Je sais c'est pour ça que je vais complètement retirer cette partie et l'heberger moi même. Si vous voulez travailler j'ai cette version du code qui fonctionne sans Discord.
[pronote_main_code_clean.zip](https://github.com/user-attachments/files/17120779/pronote_main_code_clean.zip)

**Comment by YotomiY** [comment]
J'ai réussi à faire marche le script mais j'ai 2 questions, le bot discord (qui me parait quand même utile) ne répond pas au commandes: faut-il ajouter l'Id d'un serveur ou c'un un bug. Également le script marque: il n'y a pas de menu pour aujourd'hui. Comment peu je le régler?

**Comment by TGA25dev** [comment]
Bonjour, les commandes devraient fonctionner sans problème normalement... Elle ne répondent pas ? 
Et concernant les menus cela dépend de si votre établissement les mets à disposition directement sur Pronote, je sais que c'est pas le cas pour tout le monde.

**Comment by YotomiY** [comment]
Et donc il y a une solution?

**Comment by TGA25dev** [comment]
Si ils ne sont pas dans Pronote,  je ne peux pas les inventer donc pas vraiment 😅

**Comment by YotomiY** [comment]
Par menu vous voulais dire Emploi du temps?

**Comment by TGA25dev** [comment]
Non menu de déjeuner, le repas du midi

**Comment by TGA25dev** [comment]
Hello !
Les sont sont remplis de ˋReal Time:xyz ˋ Ou il n'apparaît qu'une seule fois ??
Et pour les notifications, question bête mais vous avez bien l'appli ?

**Comment by TGA25dev** [comment]
Bizarre ça... Btw voila mon [Discord](https://discordapp.com/users/845327664143532053) si vous voulez, ce sera plus simple pour discuter 😅

**Comment by TGA25dev** [comment]
Oui pas de problème, c'est : le_tga25
